---
title: "Projektarbeit: Software Entiwicklung für Arduino - Phase 4: Neudefinition der Projektschablone"
author: "Hanan Ahmed Ashir, Mathusan Saravanapavan, Amsakan Bavan"
output: pdf_document
header-includes:
    - \renewcommand{\contentsname}{Inhaltsverzeichnis}
---

\tableofcontents

## 1 Einführung

Eine Schablone für die Arduinosoftwareentwicklung wurde gegeben. Dabei gibt es einige Verbesserungen, die bei dieser Schablone gemacht werden können. 
Eine wurde im dritten Dokument schon aufgeführt durch die Nutzung von User Stories im Requirements Engineering. Dazu können die Entwurfsprozesse der Hardware und die
Softwareentwicklungsprozesse durch agile Methoden effizienter gestaltet werden. 

# 2 Neue Schablone für Arduinosoftwareentwicklungsprojekte

Unsere neu entwickelte Projektschablone sieht wie folgt aus:

1) Einführung - Projektstart
    1.1) Projektname
    1.2) Projektbeschreibung
    1.3) Stakeholder Definition
2) Requirements Engineering durch User Stories
3) Hardwarekomponenten
    3.1) Definition eines minimalen Hardwareprototypen
    3.2) Ausarbeiten der Hardware User Stories durch agile Methoden
4) Softwareentwicklung
    4.1) Ausarbeiten der Software User Stories durch agile Methoden durch Testentwicklung
    4.2) Softwareentwicklung gegen definierte Tests