---
title: "Projektarbeit: Software Entwicklung für Arduino -  Phase 3: Requirements Engineering bei Arduino Projekten"
author: "Hanan Ahmed Ashir, Mathusan Saravanapavan, Amsakan Bavan"
output: pdf_document
header-includes:
    - \renewcommand{\contentsname}{Inhaltsverzeichnis}
---

\tableofcontents

## 1 Einführung

Im Namen der Projektarbeit, wurde uns eine Schablone beziehungsweise ein Leitfaden gegeben, um Arduino-Projekte aufzusetzen. Dieser wurde im Namen einer vorherigen 
Projektarbeit erstellt. Bei dieser ist aber aufgefallen, dass bei dieser ausgegangen wird, dass der Kunde technisches Know-How über Arduinos besitzt. Dies ist aber in der 
Berufswelt nicht immer der Fall. Dementsprechend wäre ein besserer Ansatz, User Stories zu nutzen, da diese wenig auf technische Details setzen. Darüber hinaus kann man den
iterativ, inkrementellen Ansatz für eine schenellere Prototypaufsetzung verwenden.

## 2 Definition des neuen Schablonenschemas

Das neue Schablonenschema mit den User-Stories sieht wie folgt aus: