name: Publish PDF Files
on: push

jobs:
  publish:
    name: Export Markdown files to PDF
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export PDF
        uses: lc5415/rmarkdown-action@v1
        with:
          input_file: phase1/Phase1.Rmd
          output_format: pdf_document
        
      - name: Upload PDF files
        uses: actions/upload-artifact@v4
        with:
          name: docs
